In [ ]:
import numpy as np 

In [2]:
arr = np.arange(1,13).reshape(4,3)

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
arr2 = np.arange(1,13).reshape(4,3)

In [5]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.mean(arr, axis=1)

array([ 2.,  5.,  8., 11.])

In [8]:
np.sum(arr, axis=0)

array([22, 26, 30])