In [1]:
import numpy as np

In [6]:
arr = np.array([10,20,30,40,20,50,20,30,60,90])

In [7]:
arr

array([10, 20, 30, 40, 20, 50, 20, 30, 60, 90])

In [10]:
e, u = np.unique(arr,return_counts=True)

In [12]:
e

array([10, 20, 30, 40, 50, 60, 90])

In [13]:
u

array([1, 3, 2, 1, 1, 1, 1], dtype=int64)